### ISSUE TITLE
Error scraping tool

### ISSUE THREAD

**Issue by eraserhd** [mzanibelli/errfmt#1]
Hi!

I've been thinking about writing something before I encountered this, but it isn't an _exact_ match, so I wanted to open this issue in case we're aligned.

The thing I want will deal with `make` changing directories and multiple error and grep formats at the same time.  So I wouldn't have to tell it an error format, it would scan for anything it might know, from cargo to gcc to `grep -n`.

I have two use cases in mind:

1. Piping `git grep` to a filter to add things to my Kakoune buffer that is a task list.
2. Capturing the result of the last-run command in kitty (via `kitty @ get-text`).

Actually getting the text of the last-run command and actually appending to the buffer are separate tools, I'm looking for the piece that parses the output with little or no config.

Is that something errfmt should be able to do?  Should I build something else?

Thanks!

**Comment by mzanibelli** [comment]
Hey!

Your use cases do sound interesting, but unfortunately aren't covered by this tiny program.
You could tweak it to make successive runs using all of the error formats you know, so it would aggregate all the messages on stdout.

On the other hand, I don't actually use this anymore. I wrote https://github.com/mzanibelli/kaklint instead (I just uploaded it to GH).
Why?
* leverages an external library to read error formats, that is backwards compatible with Vim errorformat syntax so I just have to Google the existing one instead of (painfully) writing my own for each and every linter I encounter
* emits Kakoune commands, so you just have to `eval %sh{kaklint $kak_buffile}` on save in your `.kakrc`, and I deleted most of the code from the standard rc lint tool (it is synchronous though)
* can handle some more specific use-cases where the linter must not target a file but a whole directory structure (ie. `cargo check`)

There is no docs so I hope you might find some interesting bits skimming through the code. Still not 100% a magic solution to your problem but another starting point 😄 

This is my `lint.kak`:

```
hook global BufWritePost .* %{ evaluate-commands %sh{
  if test -n "$kak_opt_lintcmd"; then
    kaklint "$kak_opt_lintcmd" "$kak_buffile"
  fi
}}

declare-option line-specs lint_flags
declare-option line-specs lint_messages
declare-option str lintcmd

define-command lint-show-current-line %{
    update-option buffer lint_messages
    evaluate-commands %sh{
        kakquote() { printf "%s" "$*" | sed "s/'/''/g; 1s/^/'/; \$s/\$/'/"; }
        eval set -- "${kak_quoted_opt_lint_messages}"
        shift # skip the timestamp
        while [ $# -gt 0 ]; do
            lineno=${1%%|*}
            msg=${1#*|}
            if [ "$lineno" -eq "$kak_cursor_line" ]; then
                printf "info %s\n" "$(kakquote "$msg")"
                break
            fi
            shift
        done
    }
}

define-command lint-show-diagnostics %{
  try %{
    add-highlighter window/lint flag-lines default lint_flags
    hook window -group lint-diagnostics NormalIdle .* %{ lint-show-current-line }
    hook window -group lint-diagnostics WinSetOption lint_flags=.* %{ info; lint-show-current-line }
  }
}

define-command lint-hide-diagnostics -docstring "Hide line markers and disable automatic diagnostic displaying" %{
    remove-highlighter window/lint
    remove-hooks window lint-diagnostics
}
```

The example configuration is here: https://github.com/mzanibelli/kaklint/blob/master/testdata/kaklint.json

Have a good day!
